behaviors:
  BehaviorTest:
    trainer_type: ppo
    max_steps: 1000000  # Step massimi per l'addestramento
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.02
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 128
        learning_rate: 0.0003
    keep_checkpoints: 5
    time_horizon: 64
    summary_freq: 60000
environment_parameters:
  my_environment_parameter:
    curriculum:
      # Prima lezione (iniziale)
      - name: lesson0
        completion_criteria:
          measure: progress
          behavior: BehaviorTest
          threshold: 0.20  # Cambia lezione al 20% del training 
        value: 0
      # Seconda lezione
      - name: lesson1
        completion_criteria:
          measure: progress
          behavior: BehaviorTest
          threshold: 0.40  # Cambia lezione al 40% del training 
        value: 1
      # Terza lezione
      - name: lesson2
        completion_criteria:
          measure: progress
          behavior: BehaviorTest
          threshold: 0.55  # Cambia lezione al 50% del training 
        value: 2
      # Quarta lezione
      - name: lesson3
        completion_criteria:
          measure: progress
          behavior: BehaviorTest
          threshold: 0.70  # Cambia lezione al 70% del training 
        value: 3
  
